language: rust
matrix:
  include:
    - os: windows
      rust: stable

    - os: osx
      rust: stable

    - os: linux
      rust: nightly
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    # Oldest supported version. Bump when introducing changes that need newer Rust,
    # and write that in the changelog.
    - os: linux
      rust: 1.31.0


script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then
      rustup component add rustfmt-preview;
      rustfmt --version;
      cargo fmt -- --check --unstable-features;
    else
      echo "Not checking formatting on this build";
    fi


notifications:
  email:
    on_success: never
    on_failure: never
